export enum CATEGORY {
	MACHINE1 = 'machine1',
	MACHINE2 = 'machine2',
}

export enum ORDER_STATUS {
	PENDING = 'PENDING',
	CONFIRMED = 'CONFIRMED',
	SHIPPED = 'SHIPPED',
	DELIVERED = 'DELIVERED',
	CANCELLED = 'CANCELLED',
}

export enum PAYMENT_METHOD {
	CASH = 'CASH',
	BANK_TRANSFER = 'BANK_TRANSFER',
	UPI = 'UPI',
	CARD = 'CARD',
	CHEQUE = 'CHEQUE',
}

export enum PAYMENT_STATUS {
	PENDING = 'PENDING',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
	REFUNDED = 'REFUNDED',
}
